name: CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install
        run: | 
          npm install

      - name: Cypress run
        run: |
          npm start -- --port 4200 &
          npx cypress run --env false
