name: CI
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: | 
          npm install
          
      - name: Unit tests
        run: | 
          npx jest

      - name: E2E tests
        run: |
          npm start -- --port 4200 &
          npx cypress run --env false
